"""Evidence-gated, MLX-free G0 contracts for declarative tuning.

``auto_mlx.keys``, ``auto_mlx.supervisor``, and ``auto_mlx.store_config``
are deliberately NOT imported here.  Importing this package is how any
``auto_mlx.evaluator`` (or ``executor``/``sandbox``/``measurement``) caller
gets those modules -- eagerly importing the key/supervisor modules at the
package's top level would mean every such caller transitively loads
``auto_mlx.keys`` into ``sys.modules`` just by importing anything from this
package, undermining the module boundary that keeps attestation key
material out of the evaluator's reach (see
``tests/test_supervisor.py::EvaluatorKeyIsolationTests``). Import them
directly: ``import auto_mlx.keys`` / ``from auto_mlx.supervisor import
attest_receipt`` / ``import auto_mlx.store_config``.
"""

from .canonical import (
    canonical_bytes,
    canonical_json,
    canonical_json_bytes,
    canonicalize,
    digest,
    identity,
    loads,
    parse_json,
    sha256_hex,
    sha256_identity,
    strict_json_loads,
)
from .contracts import (
    Artifact,
    CandidateProposal,
    EvaluationPolicy,
    FrozenWorkload,
    Knob,
    RuntimeIdentity,
    validate_config,
)
from .errors import (
    ArtifactIntegrityError,
    AutoMLXError,
    CanonicalJSONError,
    ContractError,
    DuplicateKeyError,
    Error,
    Failure,
    FailureCode,
    KeyMaterialError,
    StoreConfigError,
    SupervisorRefusalError,
    UnknownFieldError,
    UnsafePathError,
)
from .paths import (
    check_artifact,
    file_identity,
    safe_relative_path,
    validate_relative_posix_path,
    validate_sha256,
    verify_artifact,
)
from .providers import CandidateProvider, DeclarativeProvider
from .dispatch import (
    CANDIDATE_MODE,
    DEFAULT_MAX_AGE_NS,
    DISPATCH_SCHEMA,
    Dispatch,
    DispatchResult,
    NATIVE_MODE,
    dispatch,
    dispatch_candidate,
    resolve_dispatch,
)
from .evaluator import Evaluator, Observation, ObservationBundle
from .promotion import (
    ACTIVATE,
    DECISION_SCHEMA,
    NATIVE,
    Decision,
    PromotionDecision,
    activate,
    decision_identity,
    evaluate_promotion,
    make_promotion_decision,
    promote,
    promote_receipt,
    rollback,
    write_decision,
)
from .receipts import (
    CLAIMS_WITHHELD,
    NATIVE_FALLBACK,
    RECEIPT_SCHEMA,
    ContentAddressedStore,
    RawSample,
    Receipt,
    ReceiptStore,
    ReceiptValidation,
    read_receipt,
    receipt_identity,
    recompute_receipt_fields,
    validate_receipt,
    write_receipt,
)

__all__ = [
    "Artifact",
    "ArtifactIntegrityError",
    "AutoMLXError",
    "CandidateProposal",
    "CandidateProvider",
    "CANDIDATE_MODE",
    "CanonicalJSONError",
    "CLAIMS_WITHHELD",
    "ContentAddressedStore",
    "ContractError",
    "DECISION_SCHEMA",
    "DEFAULT_MAX_AGE_NS",
    "DISPATCH_SCHEMA",
    "DeclarativeProvider",
    "Decision",
    "Dispatch",
    "DispatchResult",
    "Error",
    "DuplicateKeyError",
    "EvaluationPolicy",
    "Evaluator",
    "Failure",
    "FailureCode",
    "FrozenWorkload",
    "KeyMaterialError",
    "Knob",
    "NATIVE",
    "NATIVE_FALLBACK",
    "NATIVE_MODE",
    "Observation",
    "ObservationBundle",
    "PromotionDecision",
    "RawSample",
    "RECEIPT_SCHEMA",
    "Receipt",
    "ReceiptStore",
    "ReceiptValidation",
    "RuntimeIdentity",
    "StoreConfigError",
    "SupervisorRefusalError",
    "UnknownFieldError",
    "UnsafePathError",
    "ACTIVATE",
    "canonical_bytes",
    "canonical_json",
    "canonical_json_bytes",
    "canonicalize",
    "check_artifact",
    "activate",
    "file_identity",
    "decision_identity",
    "dispatch",
    "dispatch_candidate",
    "evaluate_promotion",
    "identity",
    "digest",
    "loads",
    "parse_json",
    "safe_relative_path",
    "make_promotion_decision",
    "promote",
    "promote_receipt",
    "read_receipt",
    "receipt_identity",
    "recompute_receipt_fields",
    "resolve_dispatch",
    "rollback",
    "sha256_hex",
    "sha256_identity",
    "strict_json_loads",
    "validate_config",
    "validate_receipt",
    "validate_relative_posix_path",
    "validate_sha256",
    "verify_artifact",
    "write_decision",
    "write_receipt",
]
